name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test_suite:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          environment-file: environment.yml
          use-mamba: true
      - name: Run pytest with no multiprocessing
        run: pytest example
      - name: Run pytest with multiprocessing
        run: pytest -n logical example
